export const AUTH_USER = 'AUTH_USER';
export const LOGOUT = 'LOGOUT';
export const INCORRECT_USER_DATA = 'INCORRECT_USER_DATA';
export const CLEANING_INCORRECT_USER_DATA = 'CLEANING_INCORRECT_USER_DATA';
