export const mockData = [
  {
    dayName: 'Пн',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
  {
    dayName: 'Вт',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
  {
    dayName: 'Ср',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
  {
    dayName: 'Чт',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
  {
    dayName: 'Пт',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
  {
    dayName: 'Сб',
    lessons: [
      {
        time: '8:30 - 10:00',
        lessonName: 'qwe',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '10:25 - 12:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '12:35 - 14:10',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '14:30 - 16:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
      {
        time: '16:30 - 18:00',
        lessonName: '',
        type: '',
        teacher: '',
        cabinet: '',
        building: '',
      },
    ],
  },
];
